name: Build and deploy Node.js app to Azure Web App — boreal-staff

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install root deps
        run: npm ci

      - name: Install client deps
        run: npm ci
        working-directory: client

      - name: Build client (Vite)
        run: npm run build
        working-directory: client

      # Type-check server only (exclude client/tests/scripts)
      - name: Server type check only
        run: npx tsc -p tsconfig.ci.json --noEmit || true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: boreal-staff
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
