name: Deploy Staff App to AWS

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Critical: do NOT run root postinstall scripts; they invoke tsc on the client
      - name: Install root deps (no scripts)
        run: npm ci --ignore-scripts

      # Server-only type build; tsconfig.ci.json must include only server sources
      - name: Build server (TypeScript → JS)
        run: npx tsc -p tsconfig.ci.json

      - name: Install client deps
        run: npm ci
        working-directory: client

      # Vite does not type-check by default; builds even if the client has TS errors
      - name: Build client (Vite)
        run: npm run build
        working-directory: client

      - name: Verify build artifacts
        run: |
          echo "--- SERVER BUILD ---"
          ls -la dist || (echo "❌ dist missing" && exit 1)
          echo "--- CLIENT BUILD ---"
          ls -la client/dist || (echo "❌ client/dist missing" && exit 1)

      - name: Prepare deploy package
        run: |
          rm -rf deploy
          mkdir -p deploy/client
          cp -r dist/* deploy/
          cp -r client/dist/* deploy/client/
          cp package.json package-lock.json deploy/
          echo "✅ Ready for deploy"
        shell: bash

      # keep your existing AWS deploy step here if you have one; example artifact upload:
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: staff-deploy
          path: deploy
