name: Stable CI (Placeholder)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/placeholder.sh
