name: Placeholder CI Pass
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  safe-pass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/placeholder.sh
