name: security-and-audit
on:
  push:
  workflow_dispatch:

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (no postinstall)
        run: npm ci --ignore-scripts

      - name: Make scripts executable
        run: |
          chmod +x scripts/security-smoke.sh || true
          chmod +x scripts/client-audit.sh || true

      - name: Staff Security Smoke (deployed env)
        if: ${{ secrets.STAFF_BASE != '' }}
        env:
          STAFF_BASE: ${{ secrets.STAFF_BASE }}
          HTTPS_MODE: "1"
        run: ./scripts/security-smoke.sh

      - name: Client Build + Audit (repo build)
        run: |
          npm run build || true
          if [ -f scripts/client-audit.sh ]; then npm run audit:client || true; else echo "No client audit script"; fi